create table "public"."day_of_menus" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "user_id" uuid not null
);


create table "public"."items" (
    "name" character varying not null default ''::character varying,
    "user_id" uuid,
    "id" uuid not null
);

alter table "public"."employees" add column "aaaa" bigint;

CREATE UNIQUE INDEX day_of_menus_pkey ON public.day_of_menus USING btree (id);

CREATE UNIQUE INDEX items_pkey ON public.items USING btree (id);

alter table "public"."day_of_menus" add constraint "day_of_menus_pkey" PRIMARY KEY using index "day_of_menus_pkey";

alter table "public"."items" add constraint "items_pkey" PRIMARY KEY using index "items_pkey";

alter table "public"."day_of_menus" add constraint "day_of_menus_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."day_of_menus" validate constraint "day_of_menus_user_id_fkey";

alter table "public"."items" add constraint "items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."items" validate constraint "items_user_id_fkey";


